/// Process user message text to handle command-related XML tags.
/// Returns None if the message should be skipped entirely (e.g., empty local-command-stdout).
pub fn process_command_message(text: &str) -> Option<String> {
    let trimmed = text.trim();

    // Check for local-command-caveat - skip these system messages entirely
    if trimmed.starts_with("<local-command-caveat>") && trimmed.ends_with("</local-command-caveat>")
    {
        return None;
    }

    // Check for empty or whitespace-only local-command-stdout - skip these entirely
    if trimmed.starts_with("<local-command-stdout>") && trimmed.ends_with("</local-command-stdout>")
    {
        let tag_start = "<local-command-stdout>".len();
        let tag_end = trimmed.len() - "</local-command-stdout>".len();
        let inner = &trimmed[tag_start..tag_end];
        if inner.trim().is_empty() {
            return None;
        }
        // Non-empty local-command-stdout: show the content without the tags
        return Some(inner.trim().to_string());
    }

    // Check if this is a command message with <command-name> tag
    if let Some(start) = trimmed.find("<command-name>")
        && let Some(end) = trimmed.find("</command-name>")
    {
        let content_start = start + "<command-name>".len();
        if content_start < end {
            let command_name = &trimmed[content_start..end];

            // Skip /clear commands - internal context-clearing, not meaningful to display
            if command_name == "/clear" {
                return None;
            }

            // Also extract command args if present
            if let Some(args_start) = trimmed.find("<command-args>")
                && let Some(args_end) = trimmed.find("</command-args>")
            {
                let args_content_start = args_start + "<command-args>".len();
                if args_content_start < args_end {
                    let args = trimmed[args_content_start..args_end].trim();
                    if !args.is_empty() {
                        return Some(format!("{} {}", command_name, args));
                    }
                }
            }

            return Some(command_name.to_string());
        }
    }

    // Handle Cursor Agent CLI user messages wrapped in <user_query> tags,
    // optionally preceded by a <timestamp> tag
    if trimmed.contains("<user_query>") {
        let text_to_parse = strip_xml_tag(trimmed, "timestamp");
        if let Some(inner) = extract_xml_tag_content(&text_to_parse, "user_query") {
            let inner = inner.trim();
            if inner.is_empty() {
                return None;
            }
            return Some(inner.to_string());
        }
    }

    // Return original text for non-command messages
    Some(text.to_string())
}

fn extract_xml_tag_content<'a>(text: &'a str, tag: &str) -> Option<&'a str> {
    let open = format!("<{}>", tag);
    let close = format!("</{}>", tag);
    let start = text.find(&open)?;
    let content_start = start + open.len();
    let end = text[content_start..].find(&close)?;
    Some(&text[content_start..content_start + end])
}

fn strip_xml_tag(text: &str, tag: &str) -> String {
    let open = format!("<{}>", tag);
    let close = format!("</{}>", tag);
    if let Some(start) = text.find(&open)
        && let Some(close_start) = text.find(&close)
    {
        let after = close_start + close.len();
        let mut result = String::with_capacity(text.len());
        result.push_str(&text[..start]);
        result.push_str(&text[after..]);
        result
    } else {
        text.to_string()
    }
}

pub fn short_agent_id(agent_id: &str) -> &str {
    &agent_id[..agent_id.len().min(7)]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn skips_local_command_caveat() {
        let caveat = "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>";
        assert_eq!(process_command_message(caveat), None);
    }

    #[test]
    fn skips_local_command_caveat_with_whitespace() {
        let caveat = "  <local-command-caveat>Some caveat text</local-command-caveat>  ";
        assert_eq!(process_command_message(caveat), None);
    }

    #[test]
    fn preserves_normal_text() {
        assert_eq!(
            process_command_message("Hello world"),
            Some("Hello world".to_string())
        );
    }

    #[test]
    fn skips_empty_stdout() {
        assert_eq!(
            process_command_message("<local-command-stdout></local-command-stdout>"),
            None
        );
        assert_eq!(
            process_command_message("<local-command-stdout>   </local-command-stdout>"),
            None
        );
    }

    #[test]
    fn extracts_nonempty_stdout() {
        assert_eq!(
            process_command_message("<local-command-stdout>output here</local-command-stdout>"),
            Some("output here".to_string())
        );
    }

    #[test]
    fn skips_clear_command() {
        assert_eq!(
            process_command_message("<command-name>/clear</command-name>"),
            None
        );
        assert_eq!(
            process_command_message(
                "<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>"
            ),
            None
        );
    }

    #[test]
    fn extracts_other_command_names() {
        assert_eq!(
            process_command_message("<command-name>/help</command-name>"),
            Some("/help".to_string())
        );
    }

    #[test]
    fn strips_user_query_tags() {
        assert_eq!(
            process_command_message("<user_query>\nperfect thanks\n</user_query>"),
            Some("perfect thanks".to_string())
        );
    }

    #[test]
    fn strips_timestamp_and_user_query() {
        let text = "<timestamp>Thursday, May 7, 2026, 10:12 PM (UTC-7)</timestamp>\n<user_query>\nperfect thanks\n</user_query>";
        assert_eq!(
            process_command_message(text),
            Some("perfect thanks".to_string())
        );
    }

    #[test]
    fn skips_empty_user_query() {
        assert_eq!(
            process_command_message("<user_query>\n\n</user_query>"),
            None
        );
    }

    #[test]
    fn preserves_multiline_user_query() {
        let text = "<timestamp>Tuesday, Apr 28, 2026, 3:31 PM (UTC-7)</timestamp>\n<user_query>\nRun `cat /etc/services` and `seq 1 1000` exactly once each.\nDo not run any other commands.\n</user_query>";
        let result = process_command_message(text).unwrap();
        assert!(result.contains("Run `cat /etc/services`"));
        assert!(result.contains("Do not run any other commands."));
        assert!(!result.contains("<user_query>"));
        assert!(!result.contains("<timestamp>"));
    }
}
